# Generated by Django 5.0.3 on 2024-03-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_blog', models.CharField(max_length=255, verbose_name='Имя вашего блога')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='blogs/', verbose_name='Фото блога')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Мои блоги',
                'verbose_name_plural': 'Мои блоги',
            },
        ),
        migrations.CreateModel(
            name='Colleagues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя коллеги')),
                ('degree', models.CharField(max_length=255, verbose_name='Должность')),
                ('company', models.CharField(max_length=255, verbose_name='В каком компании работает')),
                ('photo', models.ImageField(upload_to='colleagues/', verbose_name='Фото коллеги')),
                ('description', models.CharField(max_length=255, verbose_name='О коллеге (Как он вам помогает)')),
            ],
            options={
                'verbose_name': 'Информация о коллег',
                'verbose_name_plural': 'Информация о коллег',
            },
        ),
        migrations.CreateModel(
            name='PersentShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_thing', models.CharField(max_length=255, verbose_name='Какие библиотеки или фреймфорки он знает')),
                ('persent', models.CharField(max_length=255, verbose_name='На сколько процентов знает')),
                ('logo', models.ImageField(upload_to='persent_show/', verbose_name='Логотип фреймфорка')),
            ],
            options={
                'verbose_name': 'Фреймфорки и скилы я знаю',
                'verbose_name_plural': 'Фреймфорки и скилы я знаю',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя проекта')),
                ('type_job', models.CharField(max_length=255, verbose_name='Какой тип работы')),
                ('image', models.ImageField(upload_to='project/')),
                ('description', models.TextField(verbose_name='Коротко о проекте')),
            ],
            options={
                'verbose_name': 'Мои проекты',
                'verbose_name_plural': 'Мои проекты',
            },
        ),
        migrations.CreateModel(
            name='Secondary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('yearsexper', models.IntegerField(verbose_name='Опыт работы пользователя')),
                ('projectfinish', models.IntegerField(verbose_name='Проекты завершенный')),
                ('happyclients', models.IntegerField(verbose_name='Счастливые клиенты')),
            ],
            options={
                'verbose_name': 'Доп информации',
                'verbose_name_plural': 'Доп информации',
            },
        ),
    ]
