# Generated by Django 5.0.3 on 2024-03-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_course', models.CharField(max_length=255, verbose_name='Когда обучался')),
                ('where_study', models.CharField(max_length=255, verbose_name='Где учился')),
                ('course_name', models.CharField(max_length=255, verbose_name='В каком курсе или университе училя')),
            ],
            options={
                'verbose_name': 'Мое оброзование',
                'verbose_name_plural': 'Мое оброзование',
            },
        ),
        migrations.CreateModel(
            name='MyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_job', models.CharField(max_length=255, verbose_name='Тип работы')),
                ('number_service', models.IntegerField(verbose_name='Номер работы (порядок)')),
                ('aboutproj', models.CharField(max_length=255, verbose_name='Коротко как я делает роботу')),
            ],
            options={
                'verbose_name': 'Мои услуги',
                'verbose_name_plural': 'Мои услуги',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typedevelop', models.CharField(max_length=255, verbose_name='Какой разработчик')),
                ('time', models.CharField(max_length=255, verbose_name='В каком году начал и закончил')),
                ('location', models.CharField(max_length=255, verbose_name='Где работал')),
            ],
            options={
                'verbose_name': 'Мой опыт',
                'verbose_name_plural': 'Мой опыт',
            },
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AlterModelOptions(
            name='infouser',
            options={'verbose_name': 'Данные пользователя', 'verbose_name_plural': 'Данные пользователя'},
        ),
        migrations.RemoveField(
            model_name='infouser',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='infouser',
            name='adress',
            field=models.CharField(default=1, max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='email',
            field=models.EmailField(default=1, max_length=255, verbose_name='Почта пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='image',
            field=models.ImageField(default=1, upload_to='info_user/', verbose_name='Фотография пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='phone_number',
            field=models.CharField(default=1, max_length=255, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='skills',
            field=models.CharField(default=1, max_length=255, verbose_name='Каким образом пользователь делает работу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infouser',
            name='work',
            field=models.CharField(max_length=255, verbose_name='Профессия пользователя'),
        ),
    ]
